---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# MultiCoex
< A tagline here>
<!-- badges: start -->
<!-- badges: end -->


## Description

The goal of MultiCoex is to create a method to better transform and utilize the 
information to provide insights into how the filtered co-expression network 
changes and aligns to reference data provides a quick and easy way to go in 
depth into co-expression analysis.

## Installation

You can install the development version of MultiCoex from [GitHub](https://github.com/) with:

``` r
require("devtools")
devtools::install_github("calebji123/MultiCoex", build_vignettes = TRUE)
library("MultiCoex")
```

To run the Shiny app:
```r
# Under construction
```

## Overview


Something about the commands
An image


## Contributions

ADD CONTRIBUTIONS HERE


## References

FULL REFERENCES


## Acknowledgements

This package was developed as part of an assessment for 2025 BCB410H: Applied 
Bioinformatics course at the University of Toronto, Toronto, 
CANADA. MultiCoex welcomes issues, enhancement requests, and other contributions. 
To submit an issue, use the GitHub issues.

